Added suru overlay to group pages
canonical-websites/insights.ubuntu.com pull request #133
Opened 2018-01-30 15:14 UTC by pmahnke

## Done

- Added suru overlay to group pages
- Small loses the overlay shape

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [group page](http://0.0.0.0:8023/cloud-and-server/)

## Issue / Card

Fixes #130

Signed-off-by: Peter Mahnke <peter@transitionelement.com>

2018-01-30 15:15 UTC, webteam-app commented
Starting demo at: http://insights.ubuntu.com-pr-133.run.demo.haus/

2018-01-30 15:36 UTC, anthonydillon requested changes
Comment in the code

QA issue:
The drop downs dont work over the new cards

2018-01-30 15:36 UTC, anthonydillon commented on static/sass/_pattern_strips.scss
> +  .suru {
Please change to `.p-strip--suru` please

2018-01-31 11:28 UTC, spencerbygraves commented
👍

2018-01-31 21:37 UTC, anthonydillon approved these changes
LGTM 👍

2018-02-01 11:07 UTC, frankiegranato commented
I can't see the demo. I see a error page: IndexError: list index out of range :-(

2018-02-01 11:10 UTC, webteam-app commented
Starting demo at: http://insights.ubuntu.com-pr-133.run.demo.haus/

2018-02-01 13:21 UTC, pmahnke commented
@frankiegranato try again

2018-02-01 13:44 UTC, frankiegranato commented
The suru fold thingy looks lovely guys.

2018-02-01 14:10 UTC, merged