Added logos and social to press centre
canonical-websites/insights.ubuntu.com pull request #147
Opened 2018-01-31 06:49 UTC by pmahnke

## Done

- Added logos and social to press centre
- Still, need to add an Announcement based archive (see #146)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [the press centre](http://0.0.0.0:8023/press-centre/)
- See that the list matches the [copy doc](https://docs.google.com/document/d/1liiT3l86LHfIyYd_Neg5LAAMRa44VF5QlF63S2gph3Q/edit#)

## Issue / Card

Fixes #132

2018-01-31 06:52 UTC, webteam-app commented
Starting demo at: http://insights.ubuntu.com-pr-147.run.demo.haus/

2018-01-31 17:37 UTC, deadlight requested changes
Comment in code.

Also, there's no gap between the last row of items nd the footer.

Lastly, there's a conflict.

Other than those small things, all looks good

2018-01-31 17:37 UTC, deadlight commented on templates/press-centre.html
> +
Some weirdness here with indenting/nesting

2018-01-31 18:07 UTC, pmahnke commented on templates/press-centre.html
> +
fixed

2018-01-31 18:17 UTC, pmahnke commented
@deadlight ready for another go

2018-02-01 08:28 UTC, deadlight approved these changes

2018-02-01 11:04 UTC, frankiegranato commented
I can't see the demo, instead I see a page that says: IndexError: list index out of range :-(

2018-02-01 13:20 UTC, pmahnke commented
@frankiegranato try this - http://insights.ubuntu.com-pr-147.run.demo.haus/press-centre/

2018-02-01 13:25 UTC, frankiegranato commented
I think we could improve the design and content-strategy for this page but, for this stage in time, ehat we have is great.

2018-02-01 14:10 UTC, merged