Removed "Tags:" label from posts if no tags present
canonical-websites/insights.ubuntu.com pull request #21
Opened 2017-10-10 15:55 UTC by Caleb-Ellis

## Done

- Added an if statement that determined that the 'Tags:' label should only show if the post contains tags

## QA

- Check that the 'Tags:' label is still present on posts with tags (e.g. [http://0.0.0.0:8023/2017/10/09/lxd-weekly-status-18/](http://0.0.0.0:8023/2017/10/09/lxd-weekly-status-18/)
- Check that the 'Tags:' label is not present on posts without tags (e.g. [http://0.0.0.0:8023/2017/10/09/lxd-weekly-status-16/](http://0.0.0.0:8023/2017/10/09/lxd-weekly-status-16/)

## Issue / Card

Fixes #3

2017-10-10 15:56 UTC, webteam-app commented
Starting demo at: http://insights.ubuntu.com-pr-21.run.demo.haus/

2017-10-11 19:53 UTC, anthonydillon requested changes
Small issue in the code.

2017-10-11 19:53 UTC, anthonydillon commented on templates/post.html
>        <p>
This `p` is not closed.

2017-10-12 08:55 UTC, Caleb-Ellis commented
Should be good now. I closed the <p> tag and moved the if statement to contain the whole <div> since there's no point rendering it in the DOM if there's no tags.

2017-10-12 20:19 UTC, anthonydillon approved these changes
Great thanks :+1:

2017-10-12 20:20 UTC, merged