436 sharing links go to the homepage
canonical-websites/insights.ubuntu.com pull request #526
Opened 2019-04-23 15:22 UTC by solazio

## Done

Update twitter share content link to take you to the post page instead of home page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8023/](http://0.0.0.0:8023/)
- Go to a blog post
- Click the Twitter share icon
- Check the generated link takes you to the post page

## Issue / Card

Fixes [436](https://github.com/canonical-web-and-design/blog.ubuntu.com/issues/436)

2019-04-23 15:23 UTC, webteam-app commented
Starting demo at: https://blog-ubuntu-com-canonical-web-and-design-pr-526.run.demo.haus/

2019-04-23 18:08 UTC, anthonydillon requested changes
This branch contains your CTA strip styling. Did you mean this?

2019-04-23 18:10 UTC, anthonydillon commented
The linkedIn share link has not been updated.

2019-04-24 08:41 UTC, solazio commented
> This branch contains your CTA strip styling. Did you mean this?

@anthonydillon No, I didn't mean to do that. I will remove it in the next commit. Sorry!

2019-04-24 12:11 UTC, anthonydillon approved these changes
LGTM :+1:

2019-04-25 08:37 UTC, merged