Deal with missing or bad data
canonical-websites/insights.ubuntu.com pull request #527
Opened 2019-04-25 09:33 UTC by pmahnke

## Done

- make headers work with categories that do not exist
- make headers work with null categories defaulting to 'Ubuntu'
- make footers add 'Article' if they do not have a type

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8023/](http://0.0.0.0:8023/)
- See that people and culture works ok
- See that footers default to text

## Issue / Card

Fixes #517

## Screenshots

**Header**
![image](https://user-images.githubusercontent.com/441217/56725456-ca3dde00-6744-11e9-881d-fd6686820ffc.png)

**Footer**
![image](https://user-images.githubusercontent.com/441217/56725810-7bdd0f00-6745-11e9-8197-5f2b3467868d.png)

2019-04-25 09:34 UTC, webteam-app commented
Starting demo at: https://blog-ubuntu-com-canonical-web-and-design-pr-527.run.demo.haus/

2019-04-25 16:25 UTC, deadlight requested changes
Try using spacing variables

2019-04-25 16:25 UTC, deadlight commented on static/sass/_pattern_card.scss
> +    padding: 1rem 1rem .5rem;
Consider using Vanilla spacing variables:
https://docs.vanillaframework.io/en/settings/spacing-settings

2019-04-25 18:01 UTC, pmahnke commented on static/sass/_pattern_card.scss
> +    padding: 1rem 1rem .5rem;
good catch... fixed.

2019-04-26 08:53 UTC, deadlight approved these changes
good stuff!

2019-04-26 08:54 UTC, merged