Added post date to posts
canonical-websites/insights.ubuntu.com pull request #87
Opened 2018-01-07 15:15 UTC by pmahnke

## Done

- Added post date to posts
- Truncated related posts excerpts
- Fixed related posts to use correct excerpt

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [any post](http://0.0.0.0:8023/2017/12/20/canonical-welcome-spotify-as-a-snap-for-linux-users/)
    - see that there is a date
    - see that the related posts are truncated at 250 chars
    - see that the replate posts excerpts are fixed

## Issue / Card

Fixes #17

Signed-off-by: Peter Mahnke <peter@transitionelement.com>

## Screenshots
### date
![image](https://user-images.githubusercontent.com/441217/34650718-798101a0-f3bd-11e7-963b-f446815de703.png)

### related posts
![image](https://user-images.githubusercontent.com/441217/34650713-6c5e8af6-f3bd-11e7-8e2c-856be180a678.png)

2018-01-07 15:16 UTC, webteam-app commented
Starting demo at: http://insights.ubuntu.com-pr-87.run.demo.haus/

2018-01-08 11:17 UTC, anthonydillon requested changes
Our standard for dates are 05 January 2017. Could you updated the formatted date to that please?

2018-01-08 14:00 UTC, pmahnke commented
@anthonydillon not sure, not without moving from that humanise thing

2018-01-08 16:07 UTC, pmahnke commented
@anthonydillon removed humanize and moved to normal datetime formatting

2018-01-08 17:04 UTC, anthonydillon approved these changes
Thanks

2018-01-08 17:04 UTC, merged